---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.20"

inputs:
- name: broker-src
  path: s3-broker
- name: broker-config

run:
  path: broker-config/tasks/test.sh
